//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Third_.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public string order_id { get; set; }
        public int customer_id { get; set; }
        public int amount { get; set; }
        public int Id { get; set; }
    }
}
